#!/bin/sh
uci -q show nodemanager >/dev/null 2>&1 || {
  uci -q batch <<'EOF'
set nodemanager.main=main
set nodemanager.main.path='/etc/nikki/profiles/config.yaml'
set nodemanager.main.template='/usr/share/nodemanager/config.template.yaml'
set nodemanager.main.fingerprint='chrome'
commit nodemanager
EOF
}
rm -f /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
